/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as AcademyIndexRouteImport } from './routes/academy.index'
import { Route as AcademyAuthenticatedRouteImport } from './routes/academy._authenticated'
import { Route as AcademyAuthRouteImport } from './routes/academy.auth'
import { Route as AcademyResetPasswordRouteImport } from './routes/academy.reset-password'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BlogStudioRouteImport } from './routes/blog.studio'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as AcademyAuthenticatedAdminRouteImport } from './routes/academy._authenticated.admin'
import { Route as AcademyAuthenticatedCalendarRouteImport } from './routes/academy._authenticated.calendar'
import { Route as AcademyAuthenticatedDashboardRouteImport } from './routes/academy._authenticated.dashboard'
import { Route as AcademyAuthenticatedGradesRouteImport } from './routes/academy._authenticated.grades'
import { Route as AcademyAuthenticatedOnboardingRouteImport } from './routes/academy._authenticated.onboarding'
import { Route as AcademyAuthenticatedTeachingRouteImport } from './routes/academy._authenticated.teaching'
import { Route as AcademyCoursesIndexRouteImport } from './routes/academy.courses.index'
import { Route as AcademyCoursesSlugRouteImport } from './routes/academy.courses.$slug'
import { Route as BlogStudioAuthenticatedRouteImport } from './routes/blog.studio._authenticated'
import { Route as BlogStudioAuthRouteImport } from './routes/blog.studio.auth'
import { Route as AcademyAuthenticatedTeachingCourseIdRouteImport } from './routes/academy._authenticated.teaching.$courseId'
import { Route as BlogStudioAuthenticatedIndexRouteImport } from './routes/blog.studio._authenticated.index'
import { Route as BlogStudioAuthenticatedPostIdRouteImport } from './routes/blog.studio._authenticated.$postId'
import { Route as BlogStudioAuthenticatedNewRouteImport } from './routes/blog.studio._authenticated.new'
import { Route as BlogStudioAuthenticatedTeamRouteImport } from './routes/blog.studio._authenticated.team'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyIndexRoute = AcademyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyAuthenticatedRoute = AcademyAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyAuthRoute = AcademyAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyResetPasswordRoute = AcademyResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AcademyRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const BlogStudioRoute = BlogStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => BlogRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyAuthenticatedAdminRoute =
  AcademyAuthenticatedAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AcademyAuthenticatedRoute,
  } as any)
const AcademyAuthenticatedCalendarRoute =
  AcademyAuthenticatedCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AcademyAuthenticatedRoute,
  } as any)
const AcademyAuthenticatedDashboardRoute =
  AcademyAuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AcademyAuthenticatedRoute,
  } as any)
const AcademyAuthenticatedGradesRoute =
  AcademyAuthenticatedGradesRouteImport.update({
    id: '/grades',
    path: '/grades',
    getParentRoute: () => AcademyAuthenticatedRoute,
  } as any)
const AcademyAuthenticatedOnboardingRoute =
  AcademyAuthenticatedOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AcademyAuthenticatedRoute,
  } as any)
const AcademyAuthenticatedTeachingRoute =
  AcademyAuthenticatedTeachingRouteImport.update({
    id: '/teaching',
    path: '/teaching',
    getParentRoute: () => AcademyAuthenticatedRoute,
  } as any)
const AcademyCoursesIndexRoute = AcademyCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyCoursesSlugRoute = AcademyCoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => AcademyRoute,
} as any)
const BlogStudioAuthenticatedRoute = BlogStudioAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => BlogStudioRoute,
} as any)
const BlogStudioAuthRoute = BlogStudioAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => BlogStudioRoute,
} as any)
const AcademyAuthenticatedTeachingCourseIdRoute =
  AcademyAuthenticatedTeachingCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => AcademyAuthenticatedTeachingRoute,
  } as any)
const BlogStudioAuthenticatedIndexRoute =
  BlogStudioAuthenticatedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BlogStudioAuthenticatedRoute,
  } as any)
const BlogStudioAuthenticatedPostIdRoute =
  BlogStudioAuthenticatedPostIdRouteImport.update({
    id: '/$postId',
    path: '/$postId',
    getParentRoute: () => BlogStudioAuthenticatedRoute,
  } as any)
const BlogStudioAuthenticatedNewRoute =
  BlogStudioAuthenticatedNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => BlogStudioAuthenticatedRoute,
  } as any)
const BlogStudioAuthenticatedTeamRoute =
  BlogStudioAuthenticatedTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => BlogStudioAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/academy/auth': typeof AcademyAuthRoute
  '/academy/reset-password': typeof AcademyResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/studio': typeof BlogStudioRouteWithChildren
  '/projects/$slug': typeof ProjectsSlugRoute
  '/academy/': typeof AcademyIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/academy/admin': typeof AcademyAuthenticatedAdminRoute
  '/academy/calendar': typeof AcademyAuthenticatedCalendarRoute
  '/academy/dashboard': typeof AcademyAuthenticatedDashboardRoute
  '/academy/grades': typeof AcademyAuthenticatedGradesRoute
  '/academy/onboarding': typeof AcademyAuthenticatedOnboardingRoute
  '/academy/teaching': typeof AcademyAuthenticatedTeachingRouteWithChildren
  '/academy/courses/$slug': typeof AcademyCoursesSlugRoute
  '/blog/studio/auth': typeof BlogStudioAuthRoute
  '/academy/courses/': typeof AcademyCoursesIndexRoute
  '/academy/teaching/$courseId': typeof AcademyAuthenticatedTeachingCourseIdRoute
  '/blog/studio/$postId': typeof BlogStudioAuthenticatedPostIdRoute
  '/blog/studio/new': typeof BlogStudioAuthenticatedNewRoute
  '/blog/studio/team': typeof BlogStudioAuthenticatedTeamRoute
  '/blog/studio/': typeof BlogStudioAuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/academy': typeof AcademyIndexRoute
  '/academy/auth': typeof AcademyAuthRoute
  '/academy/reset-password': typeof AcademyResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/studio': typeof BlogStudioAuthenticatedIndexRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/academy/admin': typeof AcademyAuthenticatedAdminRoute
  '/academy/calendar': typeof AcademyAuthenticatedCalendarRoute
  '/academy/dashboard': typeof AcademyAuthenticatedDashboardRoute
  '/academy/grades': typeof AcademyAuthenticatedGradesRoute
  '/academy/onboarding': typeof AcademyAuthenticatedOnboardingRoute
  '/academy/teaching': typeof AcademyAuthenticatedTeachingRouteWithChildren
  '/academy/courses/$slug': typeof AcademyCoursesSlugRoute
  '/blog/studio/auth': typeof BlogStudioAuthRoute
  '/academy/courses': typeof AcademyCoursesIndexRoute
  '/academy/teaching/$courseId': typeof AcademyAuthenticatedTeachingCourseIdRoute
  '/blog/studio/$postId': typeof BlogStudioAuthenticatedPostIdRoute
  '/blog/studio/new': typeof BlogStudioAuthenticatedNewRoute
  '/blog/studio/team': typeof BlogStudioAuthenticatedTeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/academy/_authenticated': typeof AcademyAuthenticatedRouteWithChildren
  '/academy/auth': typeof AcademyAuthRoute
  '/academy/reset-password': typeof AcademyResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/studio': typeof BlogStudioRouteWithChildren
  '/projects/$slug': typeof ProjectsSlugRoute
  '/academy/': typeof AcademyIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/academy/_authenticated/admin': typeof AcademyAuthenticatedAdminRoute
  '/academy/_authenticated/calendar': typeof AcademyAuthenticatedCalendarRoute
  '/academy/_authenticated/dashboard': typeof AcademyAuthenticatedDashboardRoute
  '/academy/_authenticated/grades': typeof AcademyAuthenticatedGradesRoute
  '/academy/_authenticated/onboarding': typeof AcademyAuthenticatedOnboardingRoute
  '/academy/_authenticated/teaching': typeof AcademyAuthenticatedTeachingRouteWithChildren
  '/academy/courses/$slug': typeof AcademyCoursesSlugRoute
  '/blog/studio/_authenticated': typeof BlogStudioAuthenticatedRouteWithChildren
  '/blog/studio/auth': typeof BlogStudioAuthRoute
  '/academy/courses/': typeof AcademyCoursesIndexRoute
  '/academy/_authenticated/teaching/$courseId': typeof AcademyAuthenticatedTeachingCourseIdRoute
  '/blog/studio/_authenticated/$postId': typeof BlogStudioAuthenticatedPostIdRoute
  '/blog/studio/_authenticated/new': typeof BlogStudioAuthenticatedNewRoute
  '/blog/studio/_authenticated/team': typeof BlogStudioAuthenticatedTeamRoute
  '/blog/studio/_authenticated/': typeof BlogStudioAuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academy'
    | '/blog'
    | '/contact'
    | '/cookies'
    | '/privacy'
    | '/services'
    | '/academy/auth'
    | '/academy/reset-password'
    | '/blog/$slug'
    | '/blog/studio'
    | '/projects/$slug'
    | '/academy/'
    | '/blog/'
    | '/projects/'
    | '/academy/admin'
    | '/academy/calendar'
    | '/academy/dashboard'
    | '/academy/grades'
    | '/academy/onboarding'
    | '/academy/teaching'
    | '/academy/courses/$slug'
    | '/blog/studio/auth'
    | '/academy/courses/'
    | '/academy/teaching/$courseId'
    | '/blog/studio/$postId'
    | '/blog/studio/new'
    | '/blog/studio/team'
    | '/blog/studio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/privacy'
    | '/services'
    | '/academy'
    | '/academy/auth'
    | '/academy/reset-password'
    | '/blog/$slug'
    | '/blog/studio'
    | '/projects/$slug'
    | '/blog'
    | '/projects'
    | '/academy/admin'
    | '/academy/calendar'
    | '/academy/dashboard'
    | '/academy/grades'
    | '/academy/onboarding'
    | '/academy/teaching'
    | '/academy/courses/$slug'
    | '/blog/studio/auth'
    | '/academy/courses'
    | '/academy/teaching/$courseId'
    | '/blog/studio/$postId'
    | '/blog/studio/new'
    | '/blog/studio/team'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academy'
    | '/blog'
    | '/contact'
    | '/cookies'
    | '/privacy'
    | '/services'
    | '/academy/_authenticated'
    | '/academy/auth'
    | '/academy/reset-password'
    | '/blog/$slug'
    | '/blog/studio'
    | '/projects/$slug'
    | '/academy/'
    | '/blog/'
    | '/projects/'
    | '/academy/_authenticated/admin'
    | '/academy/_authenticated/calendar'
    | '/academy/_authenticated/dashboard'
    | '/academy/_authenticated/grades'
    | '/academy/_authenticated/onboarding'
    | '/academy/_authenticated/teaching'
    | '/academy/courses/$slug'
    | '/blog/studio/_authenticated'
    | '/blog/studio/auth'
    | '/academy/courses/'
    | '/academy/_authenticated/teaching/$courseId'
    | '/blog/studio/_authenticated/$postId'
    | '/blog/studio/_authenticated/new'
    | '/blog/studio/_authenticated/team'
    | '/blog/studio/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademyRoute: typeof AcademyRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/': {
      id: '/academy/'
      path: '/'
      fullPath: '/academy/'
      preLoaderRoute: typeof AcademyIndexRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/_authenticated': {
      id: '/academy/_authenticated'
      path: ''
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyAuthenticatedRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/auth': {
      id: '/academy/auth'
      path: '/auth'
      fullPath: '/academy/auth'
      preLoaderRoute: typeof AcademyAuthRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/reset-password': {
      id: '/academy/reset-password'
      path: '/reset-password'
      fullPath: '/academy/reset-password'
      preLoaderRoute: typeof AcademyResetPasswordRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/studio': {
      id: '/blog/studio'
      path: '/studio'
      fullPath: '/blog/studio'
      preLoaderRoute: typeof BlogStudioRouteImport
      parentRoute: typeof BlogRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/_authenticated/admin': {
      id: '/academy/_authenticated/admin'
      path: '/admin'
      fullPath: '/academy/admin'
      preLoaderRoute: typeof AcademyAuthenticatedAdminRouteImport
      parentRoute: typeof AcademyAuthenticatedRoute
    }
    '/academy/_authenticated/calendar': {
      id: '/academy/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/academy/calendar'
      preLoaderRoute: typeof AcademyAuthenticatedCalendarRouteImport
      parentRoute: typeof AcademyAuthenticatedRoute
    }
    '/academy/_authenticated/dashboard': {
      id: '/academy/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/academy/dashboard'
      preLoaderRoute: typeof AcademyAuthenticatedDashboardRouteImport
      parentRoute: typeof AcademyAuthenticatedRoute
    }
    '/academy/_authenticated/grades': {
      id: '/academy/_authenticated/grades'
      path: '/grades'
      fullPath: '/academy/grades'
      preLoaderRoute: typeof AcademyAuthenticatedGradesRouteImport
      parentRoute: typeof AcademyAuthenticatedRoute
    }
    '/academy/_authenticated/onboarding': {
      id: '/academy/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/academy/onboarding'
      preLoaderRoute: typeof AcademyAuthenticatedOnboardingRouteImport
      parentRoute: typeof AcademyAuthenticatedRoute
    }
    '/academy/_authenticated/teaching': {
      id: '/academy/_authenticated/teaching'
      path: '/teaching'
      fullPath: '/academy/teaching'
      preLoaderRoute: typeof AcademyAuthenticatedTeachingRouteImport
      parentRoute: typeof AcademyAuthenticatedRoute
    }
    '/academy/courses/': {
      id: '/academy/courses/'
      path: '/courses'
      fullPath: '/academy/courses/'
      preLoaderRoute: typeof AcademyCoursesIndexRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/courses/$slug': {
      id: '/academy/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/academy/courses/$slug'
      preLoaderRoute: typeof AcademyCoursesSlugRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/blog/studio/_authenticated': {
      id: '/blog/studio/_authenticated'
      path: ''
      fullPath: '/blog/studio'
      preLoaderRoute: typeof BlogStudioAuthenticatedRouteImport
      parentRoute: typeof BlogStudioRoute
    }
    '/blog/studio/auth': {
      id: '/blog/studio/auth'
      path: '/auth'
      fullPath: '/blog/studio/auth'
      preLoaderRoute: typeof BlogStudioAuthRouteImport
      parentRoute: typeof BlogStudioRoute
    }
    '/academy/_authenticated/teaching/$courseId': {
      id: '/academy/_authenticated/teaching/$courseId'
      path: '/$courseId'
      fullPath: '/academy/teaching/$courseId'
      preLoaderRoute: typeof AcademyAuthenticatedTeachingCourseIdRouteImport
      parentRoute: typeof AcademyAuthenticatedTeachingRoute
    }
    '/blog/studio/_authenticated/': {
      id: '/blog/studio/_authenticated/'
      path: '/'
      fullPath: '/blog/studio/'
      preLoaderRoute: typeof BlogStudioAuthenticatedIndexRouteImport
      parentRoute: typeof BlogStudioAuthenticatedRoute
    }
    '/blog/studio/_authenticated/$postId': {
      id: '/blog/studio/_authenticated/$postId'
      path: '/$postId'
      fullPath: '/blog/studio/$postId'
      preLoaderRoute: typeof BlogStudioAuthenticatedPostIdRouteImport
      parentRoute: typeof BlogStudioAuthenticatedRoute
    }
    '/blog/studio/_authenticated/new': {
      id: '/blog/studio/_authenticated/new'
      path: '/new'
      fullPath: '/blog/studio/new'
      preLoaderRoute: typeof BlogStudioAuthenticatedNewRouteImport
      parentRoute: typeof BlogStudioAuthenticatedRoute
    }
    '/blog/studio/_authenticated/team': {
      id: '/blog/studio/_authenticated/team'
      path: '/team'
      fullPath: '/blog/studio/team'
      preLoaderRoute: typeof BlogStudioAuthenticatedTeamRouteImport
      parentRoute: typeof BlogStudioAuthenticatedRoute
    }
  }
}

interface AcademyAuthenticatedTeachingRouteChildren {
  AcademyAuthenticatedTeachingCourseIdRoute: typeof AcademyAuthenticatedTeachingCourseIdRoute
}

const AcademyAuthenticatedTeachingRouteChildren: AcademyAuthenticatedTeachingRouteChildren =
  {
    AcademyAuthenticatedTeachingCourseIdRoute:
      AcademyAuthenticatedTeachingCourseIdRoute,
  }

const AcademyAuthenticatedTeachingRouteWithChildren =
  AcademyAuthenticatedTeachingRoute._addFileChildren(
    AcademyAuthenticatedTeachingRouteChildren,
  )

interface AcademyAuthenticatedRouteChildren {
  AcademyAuthenticatedAdminRoute: typeof AcademyAuthenticatedAdminRoute
  AcademyAuthenticatedCalendarRoute: typeof AcademyAuthenticatedCalendarRoute
  AcademyAuthenticatedDashboardRoute: typeof AcademyAuthenticatedDashboardRoute
  AcademyAuthenticatedGradesRoute: typeof AcademyAuthenticatedGradesRoute
  AcademyAuthenticatedOnboardingRoute: typeof AcademyAuthenticatedOnboardingRoute
  AcademyAuthenticatedTeachingRoute: typeof AcademyAuthenticatedTeachingRouteWithChildren
}

const AcademyAuthenticatedRouteChildren: AcademyAuthenticatedRouteChildren = {
  AcademyAuthenticatedAdminRoute: AcademyAuthenticatedAdminRoute,
  AcademyAuthenticatedCalendarRoute: AcademyAuthenticatedCalendarRoute,
  AcademyAuthenticatedDashboardRoute: AcademyAuthenticatedDashboardRoute,
  AcademyAuthenticatedGradesRoute: AcademyAuthenticatedGradesRoute,
  AcademyAuthenticatedOnboardingRoute: AcademyAuthenticatedOnboardingRoute,
  AcademyAuthenticatedTeachingRoute:
    AcademyAuthenticatedTeachingRouteWithChildren,
}

const AcademyAuthenticatedRouteWithChildren =
  AcademyAuthenticatedRoute._addFileChildren(AcademyAuthenticatedRouteChildren)

interface AcademyRouteChildren {
  AcademyAuthenticatedRoute: typeof AcademyAuthenticatedRouteWithChildren
  AcademyAuthRoute: typeof AcademyAuthRoute
  AcademyResetPasswordRoute: typeof AcademyResetPasswordRoute
  AcademyIndexRoute: typeof AcademyIndexRoute
  AcademyCoursesSlugRoute: typeof AcademyCoursesSlugRoute
  AcademyCoursesIndexRoute: typeof AcademyCoursesIndexRoute
}

const AcademyRouteChildren: AcademyRouteChildren = {
  AcademyAuthenticatedRoute: AcademyAuthenticatedRouteWithChildren,
  AcademyAuthRoute: AcademyAuthRoute,
  AcademyResetPasswordRoute: AcademyResetPasswordRoute,
  AcademyIndexRoute: AcademyIndexRoute,
  AcademyCoursesSlugRoute: AcademyCoursesSlugRoute,
  AcademyCoursesIndexRoute: AcademyCoursesIndexRoute,
}

const AcademyRouteWithChildren =
  AcademyRoute._addFileChildren(AcademyRouteChildren)

interface BlogStudioAuthenticatedRouteChildren {
  BlogStudioAuthenticatedPostIdRoute: typeof BlogStudioAuthenticatedPostIdRoute
  BlogStudioAuthenticatedNewRoute: typeof BlogStudioAuthenticatedNewRoute
  BlogStudioAuthenticatedTeamRoute: typeof BlogStudioAuthenticatedTeamRoute
  BlogStudioAuthenticatedIndexRoute: typeof BlogStudioAuthenticatedIndexRoute
}

const BlogStudioAuthenticatedRouteChildren: BlogStudioAuthenticatedRouteChildren =
  {
    BlogStudioAuthenticatedPostIdRoute: BlogStudioAuthenticatedPostIdRoute,
    BlogStudioAuthenticatedNewRoute: BlogStudioAuthenticatedNewRoute,
    BlogStudioAuthenticatedTeamRoute: BlogStudioAuthenticatedTeamRoute,
    BlogStudioAuthenticatedIndexRoute: BlogStudioAuthenticatedIndexRoute,
  }

const BlogStudioAuthenticatedRouteWithChildren =
  BlogStudioAuthenticatedRoute._addFileChildren(
    BlogStudioAuthenticatedRouteChildren,
  )

interface BlogStudioRouteChildren {
  BlogStudioAuthenticatedRoute: typeof BlogStudioAuthenticatedRouteWithChildren
  BlogStudioAuthRoute: typeof BlogStudioAuthRoute
}

const BlogStudioRouteChildren: BlogStudioRouteChildren = {
  BlogStudioAuthenticatedRoute: BlogStudioAuthenticatedRouteWithChildren,
  BlogStudioAuthRoute: BlogStudioAuthRoute,
}

const BlogStudioRouteWithChildren = BlogStudioRoute._addFileChildren(
  BlogStudioRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogStudioRoute: typeof BlogStudioRouteWithChildren
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogStudioRoute: BlogStudioRouteWithChildren,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademyRoute: AcademyRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
